/**
 * THE RBAC POLICY — single source of truth.
 *
 * Everything that answers "may this role do X?" reads from this file:
 *
 *   - API route guards ............ `canAccessApi(role, 'GET /api/students')`
 *   - Menu / sidebar / bottom nav . `MENU`, `canAccessPage`
 *   - Page rendering .............. `canAccessPage` (main-app)
 *   - README menu matrix .......... generated by `scripts/rbac-docs.ts`
 *   - RBAC sweep expectations ..... `src/lib/rbac-routes.test.ts` reads the table
 *
 * Two rules make the tables below smaller than the code they replace:
 *
 * 1. A SUPER_ADMIN passes every gate. The platform administrator is the
 *    multi-tenant operator and can reach every school-scoped API and page;
 *    preview mode narrows the *data* it sees, never its access. So `SUPER_ADMIN`
 *    is never listed in a role array — `canAccessApi` / `canAccessPage` apply the
 *    bypass once, here. Use `hasRole` for the rare check that must NOT include
 *    the bypass (e.g. "is this account exactly a school ADMIN?").
 *
 * 2. Only the roles *above* a school's own staff appear in the tables. A school
 *    role is never listed for another school's data — that is tenant isolation
 *    (`src/lib/school-scope.ts`), a different axis from role permission.
 */
import type { AppPage } from '@/lib/stores/app-store';

/** Every role in the system, in descending order of authority. */
export const ROLES = [
  'SUPER_ADMIN',
  'ADMIN',
  'KEPALA_SEKOLAH',
  'VP_KESISWAAN',
  'WALI_KELAS',
  'GURU',
  'GURU_JAGA',
  'ORANG_TUA',
  'SISWA',
] as const;

export type Role = (typeof ROLES)[number];

export const ROLE_LABELS: Record<Role, string> = {
  SUPER_ADMIN: 'Super Admin',
  ADMIN: 'School Administrator',
  KEPALA_SEKOLAH: 'Principal',
  VP_KESISWAAN: 'Vice Principal of Student Affairs',
  WALI_KELAS: 'Homeroom Teacher',
  GURU: 'Faculty Teacher',
  GURU_JAGA: 'Duty Teacher',
  ORANG_TUA: 'Parent/Guardian',
  SISWA: 'Student',
};

/** Short column headers, for the README matrix. */
export const ROLE_COLUMNS: Record<Role, string> = {
  SUPER_ADMIN: 'Super Admin',
  ADMIN: 'Admin',
  KEPALA_SEKOLAH: 'Principal',
  VP_KESISWAAN: 'VP Kes',
  WALI_KELAS: 'Homeroom',
  GURU: 'Teacher',
  GURU_JAGA: 'Security',
  ORANG_TUA: 'Parent',
  SISWA: 'Student',
};

export function isRole(value: unknown): value is Role {
  return typeof value === 'string' && (ROLES as readonly string[]).includes(value);
}

// ─────────────────────────────── role groups ───────────────────────────────
// Named once, referenced by the page and endpoint tables below.

/** Everyone who belongs to a school (i.e. every role except the platform admin). */
export const ALL_SCHOOL_ROLES = ['ADMIN', 'KEPALA_SEKOLAH', 'VP_KESISWAAN', 'WALI_KELAS', 'GURU', 'GURU_JAGA', 'ORANG_TUA', 'SISWA'] as const satisfies readonly Role[];

/** Every member of staff (parents and students are not staff). */
export const STAFF = ['ADMIN', 'KEPALA_SEKOLAH', 'VP_KESISWAAN', 'WALI_KELAS', 'GURU', 'GURU_JAGA'] as const satisfies readonly Role[];

/** Staff without the security/duty role. */
export const HOMEROOM_AND_ABOVE = ['ADMIN', 'KEPALA_SEKOLAH', 'VP_KESISWAAN', 'WALI_KELAS', 'GURU'] as const satisfies readonly Role[];

/** Staff who take attendance and record incidents from the field. */
export const RECORDERS = ['ADMIN', 'VP_KESISWAAN', 'WALI_KELAS', 'GURU', 'GURU_JAGA'] as const satisfies readonly Role[];

/** Staff who may also correct an existing record. */
export const CLASS_LEADS = ['ADMIN', 'VP_KESISWAAN', 'WALI_KELAS'] as const satisfies readonly Role[];

/** Discipline owners: the two roles that own incidents and merit categories. */
export const DISCIPLINE_LEADS = ['ADMIN', 'VP_KESISWAAN'] as const satisfies readonly Role[];

/** School leadership: the roles that read audit trails, data rights and T&C. */
export const SITE_LEADS = ['ADMIN', 'KEPALA_SEKOLAH'] as const satisfies readonly Role[];

export const ADMIN_ONLY = ['ADMIN'] as const satisfies readonly Role[];
export const SUPER_ADMIN_ONLY = ['SUPER_ADMIN'] as const satisfies readonly Role[];
export const DUTY_MANAGER = ['VP_KESISWAAN'] as const satisfies readonly Role[];

/** Reports & Export: school-wide reporting, which a teacher's class scope can't cover. */
export const EXPORT_ROLES = ['ADMIN', 'KEPALA_SEKOLAH', 'VP_KESISWAAN', 'WALI_KELAS', 'GURU_JAGA'] as const satisfies readonly Role[];

/** Who receives an alert or may acknowledge one. */
export const ALERT_AUDIENCE = ['ADMIN', 'KEPALA_SEKOLAH', 'VP_KESISWAAN', 'WALI_KELAS', 'SISWA', 'ORANG_TUA'] as const satisfies readonly Role[];

/** Who may read school geofence settings. */
export const GEO_READERS = ['ADMIN', 'KEPALA_SEKOLAH', 'VP_KESISWAAN'] as const satisfies readonly Role[];

/** Leave requests: reading, and filing. */
export const PERMISSION_READERS = ['ADMIN', 'WALI_KELAS', 'VP_KESISWAAN', 'ORANG_TUA', 'SISWA'] as const satisfies readonly Role[];
export const PERMISSION_REQUESTERS = ['ADMIN', 'WALI_KELAS', 'ORANG_TUA', 'SISWA'] as const satisfies readonly Role[];

// ──────────────────────────────── pages / menu ────────────────────────────────

/**
 * The application menu: which pages exist, in which order, and for whom.
 * `nav-config.tsx` adds the presentation (label + icon) and nothing else.
 */
export const MENU = [
  { id: 'super-admin', roles: SUPER_ADMIN_ONLY },
  { id: 'dashboard', roles: ALL_SCHOOL_ROLES },
  { id: 'guru-jaga-monitor', roles: ['ADMIN', 'GURU_JAGA'] },
  { id: 'attendance-scanner', roles: RECORDERS },
  { id: 'attendance-records', roles: HOMEROOM_AND_ABOVE },
  { id: 'permissions', roles: ['ADMIN', 'VP_KESISWAAN', 'WALI_KELAS', 'ORANG_TUA'] },
  { id: 'violations', roles: STAFF },
  { id: 'good-deeds', roles: ['ADMIN', 'VP_KESISWAAN', 'WALI_KELAS', 'GURU'] },
  { id: 'discipline-pattern', roles: HOMEROOM_AND_ABOVE },
  { id: 'statistics', roles: ALL_SCHOOL_ROLES },
  { id: 'discipline-scan', roles: STAFF },
  { id: 'export', roles: EXPORT_ROLES },
  { id: 'id-card', roles: ['ADMIN', 'VP_KESISWAAN', 'WALI_KELAS', 'SISWA'] },
  { id: 'duty-schedule', roles: STAFF },
  { id: 'settings', roles: ALL_SCHOOL_ROLES },
  { id: 'face-capture', roles: ADMIN_ONLY },
  { id: 'audit-logs', roles: SITE_LEADS },
  { id: 'data-rights', roles: SITE_LEADS },
  { id: 'security', roles: SITE_LEADS },
  { id: 'school-documents', roles: ALL_SCHOOL_ROLES },
  { id: 'guide', roles: ALL_SCHOOL_ROLES },
  { id: 'terms', roles: ALL_SCHOOL_ROLES },
] as const satisfies readonly { id: AppPage; roles: readonly Role[] }[];

/** Every page the menu can show. `nav-config.tsx` must present each of them. */
export type MenuPage = (typeof MENU)[number]['id'];

/**
 * Pages with no menu entry that are still reachable in-app — a student profile
 * is opened from a list, not the sidebar. Kept separate so the menu parity test
 * can tell "reached from a row" apart from "someone forgot the menu item".
 */
export const OFF_MENU_PAGES: Partial<Record<AppPage, readonly Role[]>> = {
  'student-profile': ALL_SCHOOL_ROLES,
};

export const PAGE_ROLES: Partial<Record<AppPage, readonly Role[]>> = {
  ...Object.fromEntries(MENU.map((m) => [m.id, m.roles])),
  ...OFF_MENU_PAGES,
};

/** Roles the menu offers `page` to, including the Super Admin bypass. */
export function canAccessPage(role: string | undefined | null, page: AppPage): boolean {
  if (!role) return false;
  if (role === 'SUPER_ADMIN') return true;
  const allowed = PAGE_ROLES[page];
  return !!allowed && (allowed as readonly string[]).includes(role);
}

// ─────────────────────────────── API endpoints ───────────────────────────────
/**
 * One entry per (method, route) the API protects. The key is the route as the
 * app calls it; a dynamic segment is written `:id`. The value lists the school
 * roles allowed — `SUPER_ADMIN` is never listed (rule 1 in the header).
 *
 * An endpoint absent from this table has no role gate at all; add it here and
 * use `canAccessApi` in the handler rather than writing a fresh array.
 */
export const API_ROLES = {
  // Academic years — every school member reads the calendar, admin maintains it.
  'GET /api/academic-years': ALL_SCHOOL_ROLES,
  'POST /api/academic-years': ADMIN_ONLY,
  'PUT /api/academic-years': ADMIN_ONLY,
  'DELETE /api/academic-years': ADMIN_ONLY,

  // Alerts — the audience that receives them may also acknowledge them.
  'GET /api/alerts': ALERT_AUDIENCE,
  'PUT /api/alerts': ALERT_AUDIENCE,

  // Attendance — recording, correcting, reading.
  'GET /api/attendance': ALL_SCHOOL_ROLES,
  'POST /api/attendance': RECORDERS,
  'PUT /api/attendance': CLASS_LEADS,

  // Audit trail — school leadership only.
  'GET /api/audit-logs': SITE_LEADS,
  'POST /api/audit-logs': SITE_LEADS,

  // Accounts — staff may list, admin maintains. The listing itself is
  // school-scoped, so a GURU sees only the accounts of their own school.
  'GET /api/users': STAFF,
  'POST /api/users': ADMIN_ONLY,
  'PUT /api/users': ADMIN_ONLY,
  'DELETE /api/users': ADMIN_ONLY,
  'GET /api/auth': HOMEROOM_AND_ABOVE,
  'DELETE /api/auth': ADMIN_ONLY,

  // Violation & merit categories.
  'GET /api/categories': ALL_SCHOOL_ROLES,
  'POST /api/categories': DISCIPLINE_LEADS,
  'PUT /api/categories': DISCIPLINE_LEADS,
  'DELETE /api/categories': DISCIPLINE_LEADS,

  // Classes — readable by all, maintained by the admin.
  'GET /api/classes': ALL_SCHOOL_ROLES,
  'POST /api/classes': ADMIN_ONLY,
  'PUT /api/classes': ADMIN_ONLY,
  'DELETE /api/classes': ADMIN_ONLY,

  // Data-subject requests (GDPR-style).
  'GET /api/data-rights': SITE_LEADS,
  'PUT /api/data-rights': SITE_LEADS,

  // Duty roster — staff read it, the VP Student Affairs maintains it.
  'GET /api/duty-schedule': STAFF,
  'POST /api/duty-schedule': DUTY_MANAGER,
  'PUT /api/duty-schedule/:id': DUTY_MANAGER,
  'DELETE /api/duty-schedule/:id': DUTY_MANAGER,
  'POST /api/duty-schedule/substitute': DUTY_MANAGER,
  'DELETE /api/duty-schedule/substitute': DUTY_MANAGER,

  // Reporting. School-wide by nature (the class filter defaults to all), so a
  // teacher's class scope is deliberately not enough — see EXPORT_ROLES.
  'GET /api/export': EXPORT_ROLES,
  'GET /api/export-pdf': EXPORT_ROLES,

  // Face recognition — capture and verify are staff recording tools.
  'GET /api/face-references': RECORDERS,
  'POST /api/face-references': RECORDERS,
  'DELETE /api/face-references': RECORDERS,
  'GET /api/face-accuracy': RECORDERS,
  'POST /api/face-accuracy': RECORDERS,
  'POST /api/face-verify': RECORDERS,

  // Geofence — read by leadership, maintained by the admin.
  'GET /api/geofence': GEO_READERS,
  'POST /api/geofence': ADMIN_ONLY,
  'PUT /api/geofence': ADMIN_ONLY,
  'DELETE /api/geofence': ADMIN_ONLY,

  // Merit points.
  'GET /api/good-deeds': ALL_SCHOOL_ROLES,
  'POST /api/good-deeds': RECORDERS,
  'DELETE /api/good-deeds': DISCIPLINE_LEADS,

  // Bulk import (XLSX). Rows are confined to the acting school.
  'POST /api/import': DISCIPLINE_LEADS,

  // Offline queue replay.
  'GET /api/offline-sync': STAFF,
  'POST /api/offline-sync': STAFF,

  // Leave requests.
  'GET /api/permissions': PERMISSION_READERS,
  'POST /api/permissions': PERMISSION_REQUESTERS,
  'PUT /api/permissions': CLASS_LEADS,
  'DELETE /api/permissions': ADMIN_ONLY,

  // Attendance scan sessions (the in-page QR/kiosk flow).
  'POST /api/scan-session': STAFF,
  'PATCH /api/scan-session': STAFF,

  // School configuration.
  'POST /api/school-config': ADMIN_ONLY,
  'PUT /api/school-config': ADMIN_ONLY,

  // Document library — every member reads published documents; the leads also
  // see drafts and maintain the library.
  'GET /api/school-documents': ALL_SCHOOL_ROLES,
  'POST /api/school-documents': DISCIPLINE_LEADS,
  'PUT /api/school-documents': DISCIPLINE_LEADS,
  'DELETE /api/school-documents': DISCIPLINE_LEADS,

  // School profile (Settings → Profil).
  'GET /api/school-profile': SITE_LEADS,
  'PUT /api/school-profile': SITE_LEADS,

  // Analytics.
  'GET /api/statistics': ALL_SCHOOL_ROLES,

  // Students.
  'GET /api/students': ALL_SCHOOL_ROLES,
  'POST /api/students': CLASS_LEADS,
  'PUT /api/students': CLASS_LEADS,
  'DELETE /api/students': ADMIN_ONLY,

  // Subscription history of one's own school.
  'GET /api/subscription-history': SITE_LEADS,

  // Platform administration.
  'GET /api/super-admin': SUPER_ADMIN_ONLY,
  'POST /api/super-admin': SUPER_ADMIN_ONLY,

  // Terms & Conditions — reading is public, everything else is leadership.
  'POST /api/terms-content': SITE_LEADS,
  'PUT /api/terms-content': SITE_LEADS,
  'DELETE /api/terms-content': SITE_LEADS,
  'POST /api/terms-deadline': SITE_LEADS,
  'PATCH /api/terms-deadline/batch': SITE_LEADS,
  'POST /api/terms-remind': SITE_LEADS,

  // Discipline incidents.
  'GET /api/violations': ALL_SCHOOL_ROLES,
  'POST /api/violations': RECORDERS,
  'DELETE /api/violations': DISCIPLINE_LEADS,
} as const satisfies Record<string, readonly Role[]>;

export type ApiRoute = keyof typeof API_ROLES;

/**
 * Endpoints reachable without logging in. Kept here so the sweep and the docs
 * read the same list as the code.
 */
export const PUBLIC_API_ROUTES = [
  'GET /api/terms-content', // the active T&C must render on the login page
  'GET /api/scan-session', // kiosk polling, no account
  'GET /api/schools/public', // landing-page directory
  'GET /api/school-config', // branding for the landing pages
] as const;

export function isPublicApiRoute(route: string): boolean {
  return (PUBLIC_API_ROUTES as readonly string[]).includes(route);
}

/** Plain group membership — no Super Admin bypass. */
export function hasRole(role: string | undefined | null, roles: readonly Role[]): boolean {
  return !!role && (roles as readonly string[]).includes(role);
}

export function isSuperAdmin(role: string | undefined | null): boolean {
  return role === 'SUPER_ADMIN';
}

/**
 * The API authorisation check every route guard calls, including the Super
 * Admin bypass. Replaces the per-route `requireRole(role, [ ... ])` arrays.
 */
export function canAccessApi(role: string | undefined | null, route: ApiRoute): boolean {
  if (!role) return false;
  if (role === 'SUPER_ADMIN') return true;
  return hasRole(role, API_ROLES[route]);
}

/**
 * Derived view of the policy for one role — replaces the old hand-written
 * `rolePermissions` string table. Nothing maps onto an endpoint that isn't in
 * the tables above.
 */
export function permissionsFor(role: string): { pages: AppPage[]; endpoints: ApiRoute[] } {
  return {
    pages: (Object.keys(PAGE_ROLES) as AppPage[]).filter((p) => canAccessPage(role, p)),
    endpoints: (Object.keys(API_ROLES) as ApiRoute[]).filter((r) => canAccessApi(role, r)),
  };
}
